"""Full Hilbert-space definitions used for independent numerical validation."""

from __future__ import annotations

import numpy as np
import qutip as qt

from .pauli_algebra import I_GATE, X_GATE, basis_bits_to_ket, kron_all, tensor_power


STEANE_QUBITS = 7
SHOR_QUBITS = 9


def css_codewords(generator):
    """Return the binary codewords generated by ``generator`` over GF(2)."""
    generator = np.asarray(generator, dtype=int)
    n_generators = generator.shape[0]
    words = []
    for index in range(1 << n_generators):
        coefficients = np.array(
            [(index >> bit) & 1 for bit in range(n_generators)], dtype=int
        )
        words.append(coefficients @ generator % 2)
    return words


def steane_logical_states():
    """Return the logical ``|0_L>`` and ``|1_L>`` states of the Steane code."""
    generator = np.array(
        [
            [0, 0, 0, 1, 1, 1, 1],
            [0, 1, 1, 0, 0, 1, 1],
            [1, 0, 1, 0, 1, 0, 1],
        ],
        dtype=int,
    )
    logical_zero = np.sum(
        [basis_bits_to_ket(word) for word in css_codewords(generator)], axis=0
    ).astype(complex)
    logical_zero /= np.linalg.norm(logical_zero)
    logical_one = tensor_power(X_GATE, STEANE_QUBITS) @ logical_zero
    return logical_zero, logical_one


def steane_initial_state():
    """Return the Steane logical ``|+_L>`` state used in the manuscript."""
    logical_zero, logical_one = steane_logical_states()
    return (logical_zero + logical_one) / np.sqrt(2.0)


def steane_projector():
    """Return the projector onto the Steane X-stabilizer subspace."""
    supports = ({0, 2, 4, 6}, {1, 2, 5, 6}, {3, 4, 5, 6})
    identity = np.eye(1 << STEANE_QUBITS, dtype=complex)
    projector = identity
    for support in supports:
        stabilizer = kron_all(
            X_GATE if qubit in support else I_GATE
            for qubit in range(STEANE_QUBITS)
        )
        projector = projector @ (identity + stabilizer) / 2.0
    return projector


def shor_initial_state():
    """Return the Shor logical ``|+_L>`` state used in the manuscript."""
    block_zero = np.zeros(8, dtype=complex)
    block_one = np.zeros(8, dtype=complex)
    block_zero[0] = 1.0
    block_one[-1] = 1.0
    ghz_block = (block_zero + block_one) / np.sqrt(2.0)
    return kron_all([ghz_block] * 3)


def shor_projector():
    """Return the projector onto the two independent Shor X stabilizers."""
    identity = np.eye(1 << SHOR_QUBITS, dtype=complex)
    supports = (
        {0, 1, 2, 3, 4, 5},
        {3, 4, 5, 6, 7, 8},
    )
    projector = identity
    for support in supports:
        stabilizer = kron_all(
            X_GATE if qubit in support else I_GATE
            for qubit in range(SHOR_QUBITS)
        )
        projector = projector @ (identity + stabilizer) / 2.0
    return projector


def get_qubit_setup(code: str):
    """Return ``(n_qubits, initial_state, projector)`` as QuTiP objects."""
    code_lower = code.lower()
    if code_lower == "steane":
        n_qubits = STEANE_QUBITS
        state = steane_initial_state()
        projector = steane_projector()
    elif code_lower == "shor":
        n_qubits = SHOR_QUBITS
        state = shor_initial_state()
        projector = shor_projector()
    else:
        raise ValueError("code must be 'Steane' or 'Shor'.")

    ket_dims = [[2] * n_qubits, [1] * n_qubits]
    operator_dims = [[2] * n_qubits, [2] * n_qubits]
    psi0 = qt.Qobj(state.reshape(-1, 1), dims=ket_dims)
    measurement = qt.Qobj(projector, dims=operator_dims)
    return n_qubits, psi0, measurement


def _basis_projector(bits):
    ket = qt.tensor([qt.basis(2, int(bit)) for bit in bits])
    return ket * ket.dag()


def _shor_block_recovery_superoperator():
    """Return the three-qubit majority-vote X-error recovery channel."""
    identity = qt.tensor([qt.qeye(2)] * 3)
    projectors = {
        None: _basis_projector((0, 0, 0)) + _basis_projector((1, 1, 1)),
        0: _basis_projector((1, 0, 0)) + _basis_projector((0, 1, 1)),
        1: _basis_projector((0, 1, 0)) + _basis_projector((1, 0, 1)),
        2: _basis_projector((0, 0, 1)) + _basis_projector((1, 1, 0)),
    }

    channel = None
    for qubit, projector in projectors.items():
        if qubit is None:
            correction = identity
        else:
            factors = [qt.qeye(2)] * 3
            factors[qubit] = qt.sigmax()
            correction = qt.tensor(factors)
        kraus = correction * projector
        term = qt.spre(kraus) * qt.spost(kraus.dag())
        channel = term if channel is None else channel + term
    return channel


def _steane_recovery_superoperator():
    """Return the standard Steane single-X-error syndrome recovery channel."""
    supports = ({0, 2, 4, 6}, {1, 2, 5, 6}, {3, 4, 5, 6})
    stabilizers = []
    for support in supports:
        factors = [qt.qeye(2)] * STEANE_QUBITS
        for qubit in support:
            factors[qubit] = qt.sigmaz()
        stabilizers.append(qt.tensor(factors))

    identity = qt.tensor([qt.qeye(2)] * STEANE_QUBITS)
    channel = None
    for syndrome in range(8):
        projector = identity
        for bit, stabilizer in enumerate(stabilizers):
            sign = -1.0 if (syndrome >> bit) & 1 else 1.0
            projector = projector * (identity + sign * stabilizer) / 2.0

        if syndrome == 0:
            correction = identity
        else:
            factors = [qt.qeye(2)] * STEANE_QUBITS
            factors[syndrome - 1] = qt.sigmax()
            correction = qt.tensor(factors)

        kraus = correction * projector
        term = qt.spre(kraus) * qt.spost(kraus.dag())
        channel = term if channel is None else channel + term
    return channel


def build_correction_superoperator(code: str):
    """Return the discrete X-error recovery superoperator for a supported code."""
    code_lower = code.lower()
    if code_lower == "steane":
        return _steane_recovery_superoperator()
    if code_lower == "shor":
        block = _shor_block_recovery_superoperator()
        return qt.super_tensor(block, block, block)
    raise ValueError("code must be 'Steane' or 'Shor'.")
